module.exports = {
Apple: 'An apple a day keeps the doctor away. And anyone else if you throw it hard enough!',
Banana: '5 foot 6 foot 7 foot BUNCH!',
Orange: 'Orange you glad I didn'+'t say banana again?',
Air: '<div class="additive"><h3><img alt="Safe" class="rating safe" src="https://cspinet.org/sites/default/files/styles/large/public/safe1.PNG?itok=CaDbIsEE" />  AIR<a id="air" name="air"></a></h3F><p><b><span class="app-exclude">Snack foods, ice cream, breakfast cereals</span></b><br />Air is by far the cheapest food additive, and perfectly safe. Extruded snack foods such as Cheetos, breakfast cereals like Kix, and inexpensive ice creams are fluffed out with air. In the ice cream world, the amount of air whipped into the final product is called overrun. Ben and Jerrys and Häagen-Dazs vanilla ice creams weigh more than 100 grams per half cup (120 grams), so they contain roughly 20% air. Breyers vanilla ice cream weighs 67 grams per half cup, with about 45% of the volume being air. That is one reason why the premium ice creams are higher in calories they contain more actual ice cream per serving and why the cheaper (and lower-calorie) ice creams are, well, cheaper.</p><p> </p></div>',
//Aloe Vera: '<div class="additive"><h3><img alt="Avoid" class="rating avoid" src="https://cspinet.org/sites/default/files/styles/large/public/chemAvoid.gif?itok=r0T3kfA-" style="float: left; width: 26px; height: 26px;" /> <em> ALOE VERA</em><a id="aloevera" name="aloevera"></a></h3><p><b>Beverages, yogurt, desserts, flavoring.</b><br />Aloe vera, which comes from a succulent plant, is sold as a juice and is added to various other foods and supplements. It is also marketed in various skin care products, for example to treat wounds and burns. Companies make diverse health claims, but scientific evidence is scarce. The National Center for Complementary and Alternative Medicine of the National Institutes of Health concluded that <em>Aloe vera</em> "may" help heal burns and abrasions (when used topically), but there is not enough evidence to support other claims. <em>Aloe vera</em> taken orally can cause diarrhea and cramps and is recognized by FDA as a laxative. However, in 2002 FDA banned it from over-the-count//er laxatives due to a lack of safety information.</p><p>Carefully conducted studies by the U.S. government concluded that there was "clear" evidence that aloe vera extracts caused intestinal cancers in male and female rats, but not mice. The form tested, called non-decolorized whole-leaf extract of aloe vera, contains more of the components that are suspected of being cancer-causing—aloin and other anthraquinones—than do some aloe vera products on the market. (The outer leaf pulp of aloe leaves, known as the latex, contains anthraquinones). However, it is not known for sure what components of <em>Aloe vera</em> are responsible for the tumors.</p><p>The National Center for Complementary and Alternative Medicine also notes several other possible concerns: (1) people with diabetes who use glucose-lowering medication should be cautious about taking <em>Aloe vera</em> by mouth since preliminary studies suggest it may lower blood glucose levels; (2) there have been a few case reports of acute hepatitis following //oral <em>Aloe vera</em> use, but a cause-effect relationship has not been established; and (3) the diarrhea caused by the laxative effect of oral <em>Aloe vera</em> can decrease the absorption of many drugs.</p><p>Given the possible risks and unsubstantiated benefits, people should not consume <em>Aloe vera</em>. People who choose to consume it should at least look for products made with a charcoal filtration process to decolorize and remove anthraquinones, and monitored to ensure than aloin levels are low (e.g., 1 part per million or less). Some solid or semi-solid products have much higher levels of aloin. However, low levels of aloin do not guarantee safety, since it is not known for sure exactly which components of <em>Aloe vera</em> triggered cancers in rats.</p><p> </p></div>',

//Yellow 5: '<div class="additive"><h3><img alt="Avoid" class="rating avoid" src="https://cspinet.org/sites/default/files/styles/large/public/chemAvoid.gif?itok=r0T3kfA-" style="float: left; width: 26px; height: 26px;" />  <a id="yellow5" name="yellow5"></a> YELLOW 5</h3><p><b><span class="app-exclude">Artificial Coloring:</span> Gelatin dessert, candy, pet food, baked goods.</b><br />The second-most-widely used coloring causes allergy-like hypersensitivity reactions, primarily in aspirin-sensitive persons, and triggers hyperactivity in some children. It may be contaminated with such cancer-causing substances as benzidine and 4-aminobiphenyl (or chemicals that the body converts to those substances).</p></div>',

};